# Generated by Django 5.0.7 on 2024-07-29 19:34

import photo.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=photo.fields.ThumbnailImageField(upload_to="photo/%Y/%m"),
        ),
    ]
