# Generated by Django 5.0.7 on 2024-07-29 22:08

import photo.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0002_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="name",
            field=models.CharField(max_length=30, verbose_name="NAME"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=photo.fields.ThumbnailImageField(
                upload_to="photo/%Y/%m", verbose_name="IMAGE"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="upload_dt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="UPLOAD DATE"),
        ),
    ]
